mensajeria_bd:
  drivername: postgresql
  dbname: mensajeria_bd
  user: postgres
  password: 
  host: localhost
  port: 5432

etl_mensajeria:
  drivername: postgresql
  dbname: etl_mensajeria
  user: postgres
  password: 
  host: localhost
  port: 5432

LOAD_DIMENSIONS:
  True

